### ISSUE TITLE
Oracle - ZoneDateTime to TIMESTAMP WITH TIME ZONE

### ISSUE THREAD

**Issue by neocdtv** [marschall/threeten-jpa#17]
Databases:
1. Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 
2. Oracle Database 11g Express Edition Release 11.2.0.2.0 

Driver:
Oracle 12c with oracle12c_Rel1_v12.1.0.2

Oracle SQL:
"SOME_DATE" TIMESTAMP (6) WITH TIME ZONE
	
JPA with eclipseLink
@Column(name = "SOME_DATE")
private ZonedDateTime someDate;

Problem:
Converting/writing the timezone with OracleTimeConverter.writeZoneId and saving into DB.

Writing into DB:
Java-Input:
final int regionCode = ZONEIDMAP.getID("Europe/Berlin"); // regionCode is 383

DB-Output: date with timezone AUSTRALIA/MELBOURNE instead of Europe/Berlin

**Comment by marschall** [comment]
I found the issue and will do a release later today.
I hope this bug didn't cause you any issues in production.

**Comment by neocdtv** [comment]
Hi Philippe,
thank you for the fast answer. We are still not productive, so this is
currently not a real problem for us. We were kinda suprised to see Timezone
Australia and get also a defect from the Test-Team.

Regards
Krzysztof

2016-09-22 12:15 GMT+02:00 Philippe Marschall <notifications@github.com>:

**Comment by marschall** [comment]
Hi Krzysztof

I just released 1.5.1 to Maven Central, it may take a few hours until it's visible. I'm glad to hear you caught it before it went into production. Sorry for the inconvenience.

Cheers
Philippe
