### ISSUE TITLE
problem using OracleZonedDateTimeType

### ISSUE THREAD

**Issue by Jeff-Walker** [marschall/threeten-jpa#47]
I'm using hibernate 5.0.12, spring boot 1.5.9, spring data jpa 1.11.9

In my entity class:

    @Column(name = "LAST_RUN_TS")
    @Type(type = OracleZonedDateTimeType.NAME)
    private ZonedDateTime lastRun;

But I get:

    java.lang.AbstractMethodError:    
    com.github.marschall.threeten.jpa.oracle.hibernate.OracleZonedDateTimeType.nullSafeGet(Ljava/sql/ResultSet;[Ljava/lang/String;Lorg/hibernate/engine/spi/SessionImplementor;Ljava/lang/Object;)Ljava/lang/Object;

But `OracleZonedDateTimeType` has that via `AbstractTimestamptzType`. I'm can't figure out what I'm doing wrong.

I also tried `Jdbc42ZonedDateTimeType` with the same error.

**Comment by marschall** [comment]
Unfortunately we currently only support Hibernate 5.2 (see also #41). Is switching to Hibernate 5.2 an option for you? Spring Boot default so Hibernate 5.0 but [supports Hibernate 5.2](https://github.com/spring-projects/spring-boot/tree/v1.5.3.RELEASE/spring-boot-samples/spring-boot-sample-hibernate52).

Unfortunately in Hibernate 5.2 the API was changed from

```java
org.hibernate.usertype.UserType#nullSafeGet(ResultSet, String[], org.hibernate.engine.spi.SessionImplementor, Object)
```

to

```java
org.hibernate.usertype.UserType#nullSafeGet(ResultSet, String[], org.hibernate.engine.spi.SharedSessionContractImplementor, Object)
```

**Comment by Jeff-Walker** [comment]
Ok, I missed that. I was only using Hibernate 5.0 because it "came with" Spring Boot.

Thanks.
