### ISSUE TITLE
TimeZone is lost in List/Pageable but not Pojo

### ISSUE THREAD

**Issue by zol777** [marschall/threeten-jpa#55]
my oracle version 18.3 XE.

my pom.xml including the following library
```
		<dependency>
    		<groupId>com.github.marschall</groupId>
    		<artifactId>threeten-jpa-jdbc42-hibernate</artifactId>
    		<version>1.12</version>
		</dependency>
```

my jpa entiry class
```
	@Column(name = "TRANSACTION_DATE",columnDefinition= "TIMESTAMP WITH TIME ZONE")	
	@Basic(optional = false)
	@Type(type = Jdbc42ZonedDateTimeType.NAME)
	protected ZonedDateTime transactionDate;
```

my jpa repoistory contains the following method
```
	public List<Chargeback> findByCreateTsBetween(
			ZonedDateTime startTime,
			ZonedDateTime endTime);
	
	public Chargeback findByNonce(
			String nonce);
```

output of findByNonce contain the timestamp saved 
`      "transactionDate": "2020-01-05T10:15:30+08:00[Asia/Hong_Kong]",`

however output of findByCreateTsBetween does not contains timezone info
`         "transactionDate": "2020-01-05T10:15:30Z",`

if my setup or library is missed something ?

**Comment by marschall** [comment]
- You posted strings that look like JSON, do they match the values in the entities?
- What is the version of your ojdbc driver?
- What is your Hibernate version?
- Are you using Spring Data JPA? If so which version? Can you tell me what query Spring Data JPA ends up creating?
- Do both queries return the same row (same primary key)?
- Can you set a break point in `Jdbc42ZonedDateTimeType#nullSafeGet` and tell me the values returned?

**Comment by zol777** [comment]
oh that's my back . i have used your library to old table with timestamp(6) but not timestamp(6) with time zone. 

after re-creating the table with valid new column type, , it works in a proper manner 

sorry for any inconvenience  caused

**Comment by marschall** [comment]
No problem, thanks for the update. Happy to know it works for you.
